version: '3'

vars:
  DIST_DIR: "../dist"

tasks:
  licenses:
    desc: Generate a report of all licenses used in the project.
    env:
      GOWORK: off
    cmds:
      - rm './resources/licenses.txt'
      - go tool go-licenses report --ignore github.com/nobonobo/gun-shooter/host --template './resources/licenses.tmpl' ./... | fold -w 80 -s > './resources/licenses.txt'

  clean:
    desc: Clean up the assets directory.
    cmds:
      - rm -r './assets'

  pack:
    desc: Prepare assets for the game.
    cmds:
      - mkdir -p './assets'
      - go run './cmd/studio' pack ./ {{.CLI_ARGS}}

  webpack:
    desc: Prepare web assets for the game.
    cmds:
      - mkdir -p 'assets/web'
      - cp 'resources/ui/images/icon.png' 'assets/web/favicon.png'
      - cp 'resources/web/main.css' 'assets/web/main.css'
      - cp 'resources/web/main.js' 'assets/web/main.js'
      - cp 'resources/web/index.html' 'assets/index.html'
      - cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" 'assets/web/wasm_exec.js'

  wasm:
    desc: Build the game executable for the web.
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o './assets/web/main.wasm' './cmd/game'
    sources:
      - "./cmd/game/*.go"
      - "./ui/**/*.go"
    generates:
      - "./assets/web/main.wasm"

  preview:
    desc: Preview game assets.
    cmds:
      - go run './cmd/studio' preview ./ {{.CLI_ARGS}}

  debug:
    desc: Run the game in debug mode.
    cmds:
      - go run -tags debug './cmd/game'

  run:
    desc: Run the game.
    env:
      GODEBUG: cgocheck=0
    cmds:
      - go run './cmd/game'

  web:
    desc: Run a web server to serve the game.
    deps: ["build"]
    cmds:
      - go run 'github.com/mokiat/httpserv@v1.0.0' -dir './assets' -host '127.0.0.1'

  dist:
    deps: ["wasm", "webpack"]
    cmds:
      - mkdir -p "{{.DIST_DIR}}"
      - cp -Rf "./assets" "{{.DIST_DIR}}"
    sources:
      - "./cmd/game/*.go"
      - "./ui/**/*.go"
    generates:
      - "{{.DIST_DIR}}/web/main.wasm"
